color: null
description: null
fieldLayouts:
  6744e21d-8a4a-46e4-af46-a60c81dfc455:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-25T10:52:41+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Call to Action Label'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bc557db7-a951-4448-9841-83796f875d1c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-25T10:56:56+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 5472da21-93e4-472d-8c5b-c487721f2715 # Button
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64b44607-588a-4102-b335-cf732a1dde7d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: eeeb768a-dd54-4750-9c1b-1612f082c5e2
        userCondition: null
handle: callToAction
hasTitleField: true
icon: null
name: 'Call to Action'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
