color: null
description: null
fieldLayouts:
  07467c37-2958-4906-bcaa-33d05bad5cb8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-25T10:16:07+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Heading
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f50478f6-dbe7-42e9-b4cc-e6ca51512366
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-25T10:37:53+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: dccda9ee-32a2-4263-8502-f56aa033d788 # Highlight Boxes
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e294cbb-ba33-4ec9-9a7f-f80825c6cd47
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 81b7fdb1-37e8-4e47-9d5d-8af64d6c030a
        userCondition: null
handle: highlightBoxes
hasTitleField: true
icon: null
name: 'Highlight Boxes'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
