color: null
description: null
fieldLayouts:
  4309a9a8-2a39-4386-90aa-6bf960ec2312:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-25T10:46:57+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Box Heading'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 45097686-0dea-448d-b6a8-ce701f363d49
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-25T10:49:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ee67e885-07fb-43b3-8d67-edff0871c3cd # Rich Text
            handle: null
            includeInCards: false
            instructions: null
            label: 'Box Copy'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c31d612b-7ac1-4703-b646-79bbe3f43fe4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-25T10:49:41+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6ef48a00-f0c2-426a-889d-4dcc3c68d195 # Color
            handle: null
            includeInCards: false
            instructions: null
            label: 'Background Color'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73e409e8-00e4-4269-a7e4-f17bd302ad2e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bb159ff2-2590-4827-a556-01d11f754a81
        userCondition: null
handle: highlightBox
hasTitleField: true
icon: null
name: 'Highlight Box'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
