color: null
description: null
fieldLayouts:
  69673226-074a-4906-ac0d-19d08b65d393:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-11-25T10:31:49+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: 'Page Title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 93e78558-7cb7-40d8-b0a9-d0f024029fd5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-11-25T10:33:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 04874981-56dd-4100-8c16-f40c040ad508 # Page Builder
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 947f38f6-7834-4ba6-9b47-d27c1f146698
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7387380f-d335-4e84-9885-d64ea0da6eec
        userCondition: null
handle: page
hasTitleField: true
icon: null
name: Page
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
