headingLevels:
  - 1
  - 2
  - 3
name: Simple
options:
  alignment:
    options:
      - left
      - center
      - right
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - link
  - alignment
  - bulletedList
  - sourceEditing
