defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 073b2855-a336-4cd0-b263-82b6456e86f5 # Page
handle: soon
maxAuthors: 1
name: Soon
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  6f3ca0b1-e09f-4925-9771-3f667dcb00c6: # Mornington Peninsula Audiology
    enabledByDefault: true
    hasUrls: true
    template: pages/soon.twig
    uriFormat: __home__
type: single
